# Generated by Django 3.2.6 on 2022-06-04 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Foreign Language', 'Foreign Language'), ('Consumer Science', 'Consumer Science'), ('Performing Arts', 'Performing Arts'), ('Math', 'Math'), ('Business', 'Business'), ('English', 'English'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Physical Education', 'Physical Education'), ('Visual Arts', 'Visual Arts')], max_length=60)),
                ('course_number', models.SmallIntegerField(default=1, unique=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('instructor_name', models.CharField(blank=True, default='', max_length=60)),
                ('duration', models.FloatField(choices=[('45', 45), ('90', 90), ('180', 180)], default=45.0)),
            ],
        ),
    ]
