# Generated by Django 3.2.6 on 2022-06-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoclasses',
            name='duration',
        ),
        migrations.AddField(
            model_name='djangoclasses',
            name='duration_in_min',
            field=models.FloatField(choices=[('90', 90.0), ('180', 180.0), ('45', 45.0)], default=45.0),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('Foreign Language', 'Foreign Language'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Performing Arts', 'Performing Arts'), ('Physical Education', 'Physical Education'), ('Consumer Science', 'Consumer Science'), ('English', 'English'), ('Visual Arts', 'Visual Arts'), ('Computer Science', 'Computer Science'), ('Business', 'Business'), ('Math', 'Math')], max_length=60),
        ),
    ]
