# Generated by Django 3.2.6 on 2022-06-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_auto_20210831_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='duration_in_min',
            field=models.FloatField(choices=[('180', 180.0), ('45', 45.0), ('90', 90.0)], default=45.0),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('Foreign Language', 'Foreign Language'), ('Social Studies', 'Social Studies'), ('Visual Arts', 'Visual Arts'), ('Science', 'Science'), ('Consumer Science', 'Consumer Science'), ('Business', 'Business'), ('Performing Arts', 'Performing Arts'), ('Math', 'Math'), ('Computer Science', 'Computer Science'), ('English', 'English'), ('Physical Education', 'Physical Education')], max_length=60),
        ),
    ]
