# Generated by Django 3.2.6 on 2022-06-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0004_auto_20210831_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='duration_in_min',
            field=models.FloatField(choices=[('180.00', 180.0), ('90.00', 90.0), ('45.00', 45.0)], default=45),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('Performing Arts', 'Performing Arts'), ('Business', 'Business'), ('Physical Education', 'Physical Education'), ('Social Studies', 'Social Studies'), ('Math', 'Math'), ('Computer Science', 'Computer Science'), ('Consumer Science', 'Consumer Science'), ('Foreign Language', 'Foreign Language'), ('Visual Arts', 'Visual Arts'), ('Science', 'Science'), ('English', 'English')], max_length=60),
        ),
    ]
