# Generated by Django 3.2.6 on 2022-06-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0005_auto_20210831_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='duration_in_min',
            field=models.FloatField(choices=[('90.0', 90.0), ('180.0', 180.0), ('45.0', 45.0)], default=45),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('English', 'English'), ('Computer Science', 'Computer Science'), ('Social Studies', 'Social Studies'), ('Visual Arts', 'Visual Arts'), ('Business', 'Business'), ('Physical Education', 'Physical Education'), ('Consumer Science', 'Consumer Science'), ('Math', 'Math'), ('Science', 'Science'), ('Performing Arts', 'Performing Arts'), ('Foreign Language', 'Foreign Language')], max_length=60),
        ),
    ]
